/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Elf(props) {
  const { nodes, materials } = useGLTF('/christmas/elf.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        name="mesh_char_133"
        castShadow
        receiveShadow
        geometry={nodes.mesh_char_133.geometry}
        material={materials._047_David}
        morphTargetDictionary={nodes.mesh_char_133.morphTargetDictionary}
        morphTargetInfluences={nodes.mesh_char_133.morphTargetInfluences}
        scale={100}
      />
    </group>
  )
}

useGLTF.preload('/christmas/elf.glb')
